### ISSUE TITLE
python2 deprecation + code qa enforcement

### ISSUE THREAD

**Issue by ultrabug** [numberly/matterhook#3]
Quick note to:
- update setup.py to newer python versions
- deprecate python2
- update code syntax to python3
- enforce some code qa : black, isort, flake8
- travis that enforcement?

**Comment by gormux** [comment]
code syntax seems to be "python3-style" for me.
We could use fstrings in place of .format but it is >3.6 only.
I added some type enforcement on functions

I don't know how to use travis so... :)

**Comment by gormux** [comment]
I just tested travis and made a basic-but-functional pep8 check
Is there a travis app linked to this repo ?

**Comment by ultrabug** [comment]
Thanks for this @gormux
