### ISSUE TITLE
More examples for markdown attachments

### ISSUE THREAD

**Issue by gormux** [numberly/matterhook#6]
I have a few examples to illustrate how to make fancy notifications, like :

#### Title
This is a line of text
All markdown syntax works in attachments, like tables :

| name                               |   date |
|------------------------------------|--------|
| Monty Python and the Holy Grail    | :white_check_mark:  1975 |
| Monty Python's Life of Brian       | :x:  1979 |
| Monty Python's The Meaning of Life | :man_shrugging:  1983 |

with tables generated from [tabulate](https://github.com/astanin/python-tabulate) : 
```python
data = [{'name': 'Monty Python and the Holy Grail', 'date': '1975'}, {'name': 'Monty Python\'s Life of Brian', 'date': '1979'}, {'name': 'Monty Python\'s The Meaning of Life', 'date': '1983'}]
markdown_table = tabulate.tabulate(data, headers='keys')
```
Maybe an 'examples' dir would be a good idea ?

**Comment by ultrabug** [comment]
Awesome idea @gormux indeed, code samples are great!

**Comment by ultrabug** [comment]
Thanks for this @gormux
