### ISSUE TITLE
Send message directly to mattermost user.

### ISSUE THREAD

**Issue by Vox1984** [numberly/matterhook#8]
Hi

Is there a way to send message to particular mattermost user with your lib?

**Comment by ultrabug** [comment]
Hey @Vox1984 

Sure, just use "@username" as the target channel name :)

**Comment by Vox1984** [comment]
@ultrabug 
Perfect! It works!
If anyone looks into it:
`mwh.send('coconut webhook message', channel='@john.doe')`

Thank you.

**Comment by ultrabug** [comment]
Sure mate, enjoy!
