### ISSUE TITLE
support for receiving messages on a channel

### ISSUE THREAD

**Issue by Vox1984** [numberly/matterhook#9]
Hi,

I am using your lib and it works super for sending out message. I would like to extend the functionality though, so the mattermost user can send some information back - for example to regulate the verbosity of messages.

Is it supported?

**Comment by ultrabug** [comment]
Hi @Vox1984 

Thanks for your kind words :)

I'm afraid this lib aims at pushing information to Mattermost, not receiving it as it does not implement a web server.

So the short answer is no.
